; This Source Code Form is subject to the terms of the Mozilla Public
; License, v. 2.0. If a copy of the MPL was not distributed with this
; file, You can obtain one at https://mozilla.org/MPL/2.0/.

#lang racket

(require
  "../assembler.rkt"
  "../opcodes.rkt")

(provide (all-defined-out))

(define test-cases
  (list                         ; rd funct3          rs1  rs2       imm  alu-fn   use-pc? use-imm? has-rd? load? store? jump? branch? mret?
    ; Test rd, rs1, rs2 for R-type instruction.
    (list (ADD    0  0      0)     0 funct3-add-sub    0    0      'any 'alu-add  #f      #f       #f      #f    #f     #f    #f      #f)
    (list (ADD    5 10     15)     5 funct3-add-sub   10   15      'any 'alu-add  #f      #f       #t      #f    #f     #f    #f      #f)
    (list (ADD   31 31     31)    31 funct3-add-sub   31   31      'any 'alu-add  #f      #f       #t      #f    #f     #f    #f      #f)
    (list (ADD   40 41     42)     8 funct3-add-sub    9   10      'any 'alu-add  #f      #f       #t      #f    #f     #f    #f      #f)
    ; Test imm for I-type instruction (12 bits)
    (list (ADDI   5 10      0)     5 funct3-add-sub   10 'any         0 'alu-add  #f      #t       #t      #f    #f     #f    #f      #f)
    (list (ADDI   5 10 #x07ff)     5 funct3-add-sub   10 'any    #x07ff 'alu-add  #f      #t       #t      #f    #f     #f    #f      #f)
    (list (ADDI   5 10 #x0800)     5 funct3-add-sub   10 'any   #x-0800 'alu-add  #f      #t       #t      #f    #f     #f    #f      #f)
    (list (ADDI   5 10 #x0fff)     5 funct3-add-sub   10 'any        -1 'alu-add  #f      #t       #t      #f    #f     #f    #f      #f)
    ; Test imm for S-type instruction (12 bits)
    (list (SW     5 10      0)  'any funct3-lw-sw     10    5         0 'alu-add  #f      #t       #f      #f    #t     #f    #f      #f)
    (list (SW     5 10 #x07ff)  'any funct3-lw-sw     10    5    #x07ff 'alu-add  #f      #t       #f      #f    #t     #f    #f      #f)
    (list (SW     5 10 #x0800)  'any funct3-lw-sw     10    5   #x-0800 'alu-add  #f      #t       #f      #f    #t     #f    #f      #f)
    (list (SW     5 10 #x0fff)  'any funct3-lw-sw     10    5        -1 'alu-add  #f      #t       #f      #f    #t     #f    #f      #f)
    ; Test imm for B-type instruction (13 bits, even)
    (list (BEQ    5 10      0)  'any funct3-beq        5   10         0 'alu-add  #t      #t       #f      #f    #f     #f    #t      #f)
    (list (BEQ    5 10 #x0fff)  'any funct3-beq        5   10    #x0ffe 'alu-add  #t      #t       #f      #f    #f     #f    #t      #f)
    (list (BEQ    5 10 #x1000)  'any funct3-beq        5   10   #x-1000 'alu-add  #t      #t       #f      #f    #f     #f    #t      #f)
    (list (BEQ    5 10 #x1fff)  'any funct3-beq        5   10        -2 'alu-add  #t      #t       #f      #f    #f     #f    #t      #f)
    ; Test imm for U-type instruction (32 bits, multiple of #x1000)
    (list (LUI    5    #x0000)     5 'any           'any 'any         0 'alu-nop  #f      #t       #t      #f    #f     #f    #f      #f)
    (list (LUI    5    #x0fff)     5 'any           'any 'any         0 'alu-nop  #f      #t       #t      #f    #f     #f    #f      #f)
    (list (LUI    5    #x1fff)     5 'any           'any 'any    #x1000 'alu-nop  #f      #t       #t      #f    #f     #f    #f      #f)
    (list (LUI    5    #xffff)     5 'any           'any 'any    #xf000 'alu-nop  #f      #t       #t      #f    #f     #f    #f      #f)
    (list (LUI    5        -1)     5 'any           'any 'any   #x-1000 'alu-nop  #f      #t       #t      #f    #f     #f    #f      #f)
    ; Test imm for J-type instruction (21 bits, even)
    (list (JAL    5         0)     5 'any           'any 'any         0 'alu-add  #t      #t       #t      #f    #f     #t    #f      #f)
    (list (JAL    5   #xfffff)     5 'any           'any 'any   #xffffe 'alu-add  #t      #t       #t      #f    #f     #t    #f      #f)
    (list (JAL    5  #x100000)     5 'any           'any 'any #x-100000 'alu-add  #t      #t       #t      #f    #f     #t    #f      #f)
    (list (JAL    5  #x1fffff)     5 'any           'any 'any        -2 'alu-add  #t      #t       #t      #f    #f     #t    #f      #f)
    ; Test functions for all instruction types.
    (list (LUI    0    #x1234)  'any 'any           'any 'any      'any 'alu-nop  #f      #t       #f      #f    #f     #f    #f      #f)
    (list (LUI   31    #x1234)  'any 'any           'any 'any      'any 'alu-nop  #f      #t       #t      #f    #f     #f    #f      #f)
    (list (AUIPC  0    #x1234)  'any 'any           'any 'any      'any 'alu-add  #t      #t       #f      #f    #f     #f    #f      #f)
    (list (AUIPC 31    #x1234)  'any 'any           'any 'any      'any 'alu-add  #t      #t       #t      #f    #f     #f    #f      #f)
    (list (JAL    0    #x1234)  'any 'any           'any 'any      'any 'alu-add  #t      #t       #f      #f    #f     #t    #f      #f)
    (list (JAL   31    #x1234)  'any 'any           'any 'any      'any 'alu-add  #t      #t       #t      #f    #f     #t    #f      #f)
    (list (JALR   0 15 #x1234)  'any funct3-jalr    'any 'any      'any 'alu-add  #f      #t       #f      #f    #f     #t    #f      #f)
    (list (JALR  31 15 #x1234)  'any funct3-jalr    'any 'any      'any 'alu-add  #f      #t       #t      #f    #f     #t    #f      #f)
    (list (BEQ    5 10 #x1234)  'any funct3-beq     'any 'any      'any 'alu-add  #t      #t       #f      #f    #f     #f    #t      #f)
    (list (BNE    5 10 #x1234)  'any funct3-bne     'any 'any      'any 'alu-add  #t      #t       #f      #f    #f     #f    #t      #f)
    (list (BLT    5 10 #x1234)  'any funct3-blt     'any 'any      'any 'alu-add  #t      #t       #f      #f    #f     #f    #t      #f)
    (list (BGE    5 10 #x1234)  'any funct3-bge     'any 'any      'any 'alu-add  #t      #t       #f      #f    #f     #f    #t      #f)
    (list (BLTU   5 10 #x1234)  'any funct3-bltu    'any 'any      'any 'alu-add  #t      #t       #f      #f    #f     #f    #t      #f)
    (list (BGEU   5 10 #x1234)  'any funct3-bgeu    'any 'any      'any 'alu-add  #t      #t       #f      #f    #f     #f    #t      #f)
    (list (LB     0 15 #x1234)  'any funct3-lb-sb   'any 'any      'any 'alu-add  #f      #t       #f      #t    #f     #f    #f      #f)
    (list (LB    31 15 #x1234)  'any funct3-lb-sb   'any 'any      'any 'alu-add  #f      #t       #t      #t    #f     #f    #f      #f)
    (list (LH     0 15 #x1234)  'any funct3-lh-sh   'any 'any      'any 'alu-add  #f      #t       #f      #t    #f     #f    #f      #f)
    (list (LH    31 15 #x1234)  'any funct3-lh-sh   'any 'any      'any 'alu-add  #f      #t       #t      #t    #f     #f    #f      #f)
    (list (LW     0 15 #x1234)  'any funct3-lw-sw   'any 'any      'any 'alu-add  #f      #t       #f      #t    #f     #f    #f      #f)
    (list (LW    31 15 #x1234)  'any funct3-lw-sw   'any 'any      'any 'alu-add  #f      #t       #t      #t    #f     #f    #f      #f)
    (list (LBU    0 15 #x1234)  'any funct3-lbu     'any 'any      'any 'alu-add  #f      #t       #f      #t    #f     #f    #f      #f)
    (list (LBU   31 15 #x1234)  'any funct3-lbu     'any 'any      'any 'alu-add  #f      #t       #t      #t    #f     #f    #f      #f)
    (list (LHU    0 15 #x1234)  'any funct3-lhu     'any 'any      'any 'alu-add  #f      #t       #f      #t    #f     #f    #f      #f)
    (list (LHU   31 15 #x1234)  'any funct3-lhu     'any 'any      'any 'alu-add  #f      #t       #t      #t    #f     #f    #f      #f)
    (list (SB     5 15 #x1234)  'any funct3-lb-sb   'any 'any      'any 'alu-add  #f      #t       #f      #f    #t     #f    #f      #f)
    (list (SH     5 15 #x1234)  'any funct3-lh-sh   'any 'any      'any 'alu-add  #f      #t       #f      #f    #t     #f    #f      #f)
    (list (SW     5 15 #x1234)  'any funct3-lw-sw   'any 'any      'any 'alu-add  #f      #t       #f      #f    #t     #f    #f      #f)
    (list (ADDI   0 10 #x1234)  'any funct3-add-sub 'any 'any      'any 'alu-add  #f      #t       #f      #f    #f     #f    #f      #f)
    (list (ADDI  31 10 #x1234)  'any funct3-add-sub 'any 'any      'any 'alu-add  #f      #t       #t      #f    #f     #f    #f      #f)
    (list (SLLI   0 10 #x1234)  'any funct3-sll     'any 'any      'any 'alu-sll  #f      #t       #f      #f    #f     #f    #f      #f)
    (list (SLLI  31 10 #x1234)  'any funct3-sll     'any 'any      'any 'alu-sll  #f      #t       #t      #f    #f     #f    #f      #f)
    (list (SLTI   0 10 #x1234)  'any funct3-slt     'any 'any      'any 'alu-slt  #f      #t       #f      #f    #f     #f    #f      #f)
    (list (SLTI  31 10 #x1234)  'any funct3-slt     'any 'any      'any 'alu-slt  #f      #t       #t      #f    #f     #f    #f      #f)
    (list (SLTIU  0 10 #x1234)  'any funct3-sltu    'any 'any      'any 'alu-sltu #f      #t       #f      #f    #f     #f    #f      #f)
    (list (SLTIU 31 10 #x1234)  'any funct3-sltu    'any 'any      'any 'alu-sltu #f      #t       #t      #f    #f     #f    #f      #f)
    (list (XORI   0 10 #x1234)  'any funct3-xor     'any 'any      'any 'alu-xor  #f      #t       #f      #f    #f     #f    #f      #f)
    (list (XORI  31 10 #x1234)  'any funct3-xor     'any 'any      'any 'alu-xor  #f      #t       #t      #f    #f     #f    #f      #f)
    (list (SRLI   0 10 #x1234)  'any funct3-srl-sra 'any 'any      'any 'alu-srl  #f      #t       #f      #f    #f     #f    #f      #f)
    (list (SRLI  31 10 #x1234)  'any funct3-srl-sra 'any 'any      'any 'alu-srl  #f      #t       #t      #f    #f     #f    #f      #f)
    (list (SRAI   0 10 #x1234)  'any funct3-srl-sra 'any 'any      'any 'alu-sra  #f      #t       #f      #f    #f     #f    #f      #f)
    (list (SRAI  31 10 #x1234)  'any funct3-srl-sra 'any 'any      'any 'alu-sra  #f      #t       #t      #f    #f     #f    #f      #f)
    (list (ORI    0 10 #x1234)  'any funct3-or      'any 'any      'any 'alu-or   #f      #t       #f      #f    #f     #f    #f      #f)
    (list (ORI   31 10 #x1234)  'any funct3-or      'any 'any      'any 'alu-or   #f      #t       #t      #f    #f     #f    #f      #f)
    (list (ANDI   0 10 #x1234)  'any funct3-and     'any 'any      'any 'alu-and  #f      #t       #f      #f    #f     #f    #f      #f)
    (list (ANDI  31 10 #x1234)  'any funct3-and     'any 'any      'any 'alu-and  #f      #t       #t      #f    #f     #f    #f      #f)
    (list (ADD    0  5     10)  'any funct3-add-sub 'any 'any      'any 'alu-add  #f      #f       #f      #f    #f     #f    #f      #f)
    (list (ADD   31  5     10)  'any funct3-add-sub 'any 'any      'any 'alu-add  #f      #f       #t      #f    #f     #f    #f      #f)
    (list (SUB    0  5     10)  'any funct3-add-sub 'any 'any      'any 'alu-sub  #f      #f       #f      #f    #f     #f    #f      #f)
    (list (SUB   31  5     10)  'any funct3-add-sub 'any 'any      'any 'alu-sub  #f      #f       #t      #f    #f     #f    #f      #f)
    (list (SLL    0  5     10)  'any funct3-sll     'any 'any      'any 'alu-sll  #f      #f       #f      #f    #f     #f    #f      #f)
    (list (SLL   31  5     10)  'any funct3-sll     'any 'any      'any 'alu-sll  #f      #f       #t      #f    #f     #f    #f      #f)
    (list (SLT    0  5     10)  'any funct3-slt     'any 'any      'any 'alu-slt  #f      #f       #f      #f    #f     #f    #f      #f)
    (list (SLT   31  5     10)  'any funct3-slt     'any 'any      'any 'alu-slt  #f      #f       #t      #f    #f     #f    #f      #f)
    (list (SLTU   0  5     10)  'any funct3-sltu    'any 'any      'any 'alu-sltu #f      #f       #f      #f    #f     #f    #f      #f)
    (list (SLTU  31  5     10)  'any funct3-sltu    'any 'any      'any 'alu-sltu #f      #f       #t      #f    #f     #f    #f      #f)
    (list (XOR    0  5     10)  'any funct3-xor     'any 'any      'any 'alu-xor  #f      #f       #f      #f    #f     #f    #f      #f)
    (list (XOR   31  5     10)  'any funct3-xor     'any 'any      'any 'alu-xor  #f      #f       #t      #f    #f     #f    #f      #f)
    (list (SRL    0  5     10)  'any funct3-srl-sra 'any 'any      'any 'alu-srl  #f      #f       #f      #f    #f     #f    #f      #f)
    (list (SRL   31  5     10)  'any funct3-srl-sra 'any 'any      'any 'alu-srl  #f      #f       #t      #f    #f     #f    #f      #f)
    (list (SRA    0  5     10)  'any funct3-srl-sra 'any 'any      'any 'alu-sra  #f      #f       #f      #f    #f     #f    #f      #f)
    (list (SRA   31  5     10)  'any funct3-srl-sra 'any 'any      'any 'alu-sra  #f      #f       #t      #f    #f     #f    #f      #f)
    (list (OR     0  5     10)  'any funct3-or      'any 'any      'any 'alu-or   #f      #f       #f      #f    #f     #f    #f      #f)
    (list (OR    31  5     10)  'any funct3-or      'any 'any      'any 'alu-or   #f      #f       #t      #f    #f     #f    #f      #f)
    (list (AND    0  5     10)  'any funct3-and     'any 'any      'any 'alu-and  #f      #f       #f      #f    #f     #f    #f      #f)
    (list (AND   31  5     10)  'any funct3-and     'any 'any      'any 'alu-and  #f      #f       #t      #f    #f     #f    #f      #f)))
    ;                             rd funct3          rs1  rs2       imm  alu-fn   use-pc? use-imm? has-rd? load? store? jump? branch? mret?
